
# This is a basic workflow to help you get started with Actions

name: create release

on:
  push:
    tags:
      - 'b*'

jobs:
  read-build-number:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: read file
        uses: juliangruber/read-file-action@v1
        id: read-build-number
        with:
          path: ./BUILD
    
    outputs:
      build-number: ${{ steps.read-build-number.outputs.content }}
  
  release:
    needs: [read-build-number]
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            BUILD
