
# This is a basic workflow to help you get started with Actions

name: create release

on:
  push:
    tags:
      - 'b*'

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: upload app
        uses: actions/upload-artifact@v2
        with:
          name: app-macos
          path: sample-app-macos.app

  release:
    needs: [upload]
    runs-on: ubuntu-latest
    
    steps:
      - name: download app
        uses: actions/download-artifact@v2
        with:
          name: app-macos
          path: sample-app-macos.app

      - name: zip app bundle
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r sample-app-macos.app.zip sample-app-macos.app
        
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            BUILD
            VERSION
            sample-app-macos.app.zip
