
# This is a basic workflow to help you get started with Actions

name: create release

on:
  push:
    tags:
      - 'b*'

jobs:
  release:
    needs: [read-build-number]
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            BUILD
            VERSION
