
# This is a basic workflow to help you get started with Actions

name: create release

on:
  push:
    tags:
      - 'b*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: zip app bundle
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r sample-app-macos.app.zip sample-app-macos.app
        
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            BUILD
            VERSION
            sample-app-macos.app.zip
