
# This is a basic workflow to help you get started with Actions

name: test

on:
  workflow_dispatch:

jobs:
  install-ndk:
    runs-on: windows-latest

    steps:
      - name: read file
        uses: juliangruber/read-file-action@v1
        id: read-build-number
        with:
          path: ./BUILD
          
      - run: echo ${{ steps.read-build-number.outputs.content }}
