
# This is a basic workflow to help you get started with Actions

name: read build number

on:
  workflow_dispatch:

jobs:
  read-build-number:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: read file
        uses: juliangruber/read-file-action@v1
        id: read-build-number
        with:
          path: ./BUILD
          
      - run: echo ${{ steps.read-build-number.outputs.content }}
