# This is a basic workflow to help you get started with Actions

name: test

on:
  workflow_dispatch:

jobs:
  install-ndk:
    runs-on: macos-latest

    steps:
      - name: install ndk 
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22b
          add-to-path: false
          
      - run: ${NDK_ROOT}/ndk-build
        env:
          NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
